#!/usr/bin/python3
import datetime
import os
import pwd
import subprocess
from itertools import repeat

months=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']


print('''
A: Vacation
B: Sickness
C: Caring of a sick child
D: Absence without pay
E: Other reason
''')

table_from = list(repeat('' ,10))
table_to = list(repeat('' ,10))
table_duration = list(repeat('' ,10))
table_reason = list(repeat('' ,10))

index = 0
all_presence = 'YES'
while True:
    from_ = input('From (dd/mm): ')
    if not from_:
        break
    all_presence = ''
    to = input('To (dd/mm): ')
    reason = input('Reason: ').upper()

    fday, fmonth = [int(i) for i in from_.split('/')]
    tday, tmonth = [int(i) for i in to.split('/')]
    month = datetime.datetime.now().month
    year = datetime.datetime.now().year
    fyear = year - 1 if fmonth == 12 and month == 1 else year
    tyear = year - 1 if tmonth == 12 and month == 1 else year

    date_from = datetime.date(fyear, fmonth, fday)
    date_to = datetime.date(tyear, tmonth, tday)

    days = (date_to - date_from).days + 1

    table_from[index] = f'{fyear}/{fmonth:02}/{fday:02}'
    table_to[index] = f'{tyear}/{tmonth:02}/{tday:02}'
    table_duration[index] = f'{days}'
    table_reason[index] = f'{reason}'

    index += 1

name = pwd.getpwnam(os.environ['USER']).pw_gecos.split(',', 1)[0]

with open('template.html', 'rt') as f:
    template = f.read()

current_month_number = datetime.datetime.now().month if datetime.datetime.now().day <= 16 else datetime.datetime.now().month + 1
cmonth = months[current_month_number - 1]
pmonth = months[current_month_number - 2]

jop = template.format(
    year=datetime.datetime.now().year,
    cmonth=cmonth,
    pmonth=pmonth,
    current_month_number=current_month_number,
    employee_number='SW0020',
    all_presence=all_presence,
    name=name,
    table_from=table_from,
    table_to=table_to,
    table_duration=table_duration,
    table_reason=table_reason,
)

# Create HTML file
print('Generating…')
htmlfile = 'jop-' + str(datetime.datetime.now().date()) + '.html'
with open(htmlfile, 'wt') as f:
    f.write(jop)

# Convert it to pdf using chromium
print('Converting to pdf…')
subprocess.check_call([
    '/usr/bin/chromium', # Full path or it starts with firejail
    '--no-sandbox',
    '--headless',
    '--disable-gpu',
    '--print-to-pdf',
    htmlfile
])
jopfile = 'jop-' + str(datetime.datetime.now().date()) + '.pdf'
os.rename('output.pdf', jopfile)
os.unlink(htmlfile)

print('Signing journal of presence file…')
subprocess.check_call(['gpg', '--armour', '--output', jopfile + '.asc', '--detach-sign', jopfile])

print(f'JOP stored in {jopfile}')
open_in_viewer = input('Do you want to open it? (y/N)')

if open_in_viewer.lower().startswith('y'):
    subprocess.check_call(['okular', jopfile], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

send = input('Do you want to send it to Thomas? (y/N)')
if send.lower().startswith('y'):
    pipe = os.pipe()
    rfile = os.fdopen(pipe[0], mode='r')
    wfile = os.fdopen(pipe[1], mode='w')
    wfile.write("Ack?")
    wfile.close()
    subprocess.check_call(['lsi-send', '-F', jopfile, 'thomas.cellerier'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    subprocess.check_call(['lsi-send', '-F', jopfile + '.asc', 'thomas.cellerier'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    subprocess.check_call(['lsi-write', 'thomas.cellerier'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, stdin=rfile)
